DROP DATABASE IF EXISTS DBSOCORRODESK;
CREATE DATABASE DBSOCORRODESK;

USE DBSOCORRODESK;

CREATE TABLE TIPOUSUARIO (
IDTIPOUSUARIO INT NOT NULL PRIMARY KEY AUTO_INCREMENT
, DESCRICAO VARCHAR(255)
);

CREATE TABLE USUARIO (
IDUSUARIO INT NOT NULL PRIMARY KEY AUTO_INCREMENT
, IDTIPOUSUARIO INT, FOREIGN KEY (IDTIPOUSUARIO) REFERENCES TIPOUSUARIO (IDTIPOUSUARIO)
, NOME VARCHAR(255)
, CPF CHAR(11) 
, EMAIL VARCHAR(255)
, DATACADASTRO DATE
, DATAEXPIRACAO DATE
, LOGIN VARCHAR(255)
, SENHA VARCHAR(255)
);

CREATE TABLE CHAMADOS (
IDCHAMADO INT NOT NULL PRIMARY KEY AUTO_INCREMENT
, IDUSUARIO INT, FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO (IDUSUARIO)
, IDTECNICO INT, FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO (IDUSUARIO)
, TITULO VARCHAR(255)
, DESCRICAO VARCHAR(255)
, DATAABERTURA DATE 
, SOLUCAO VARCHAR(255)
, DATAFECHAMENTO DATE 
);

INSERT INTO TIPOUSUARIO (descricao) VALUES ('ADMINISTRADOR');
INSERT INTO TIPOUSUARIO (descricao) VALUES ('TECNICO');
INSERT INTO TIPOUSUARIO (descricao) VALUES ('USUARIO');

INSERT INTO USUARIO (idtipousuario, nome, cpf, email, datacadastro, dataexpiracao, login, senha) VALUES (1, 'Vinicius', '08511653970', 
		'vinix.correia@gmail.com', '2021-09-12', null, 'vinicius', 'surfdsh2');
